name: Mattyhues
favicon: null
layout_spectrum: 0.5716457555536181
typography_spectrum: 0.9373195669613779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9808803859632462
  lightness: 0.2624491669703275
  saturation: 0.989365650806576
  rhythmicContrast: 0.3163632289506495
purpose: []
